export const LOCATION_KEYWORDS = {
  owerri: [
    'perfume shop in Owerri',
    'perfume store in Owerri',
    'best perfume store in Owerri',
    'best perfume shop in Owerri',
    'where to buy original perfume in Owerri',
    'perfume delivery in Owerri',
    'perfume vendor in Owerri',
    'buy perfumes online in Owerri',
    'designer perfume Owerri',
    'Arabian perfume Owerri',
    'oil perfume Owerri',
    'body mist Owerri',
    'diffuser Owerri',
    'humidifier Owerri',
    'perfume gift set Owerri',
  ],
  imo: [
    'perfume shop in Imo State',
    'perfume store Imo State',
    'buy perfume in Imo State',
    'fragrance shop Imo State',
    'online perfume store Imo State',
    'perfume vendor Imo State',
  ],
  portHarcourt: [
    'perfume shop in Port Harcourt',
    'buy perfume in Port Harcourt',
    'perfume delivery Port Harcourt',
    'original perfume Port Harcourt',
    'designer perfume Port Harcourt',
    'fragrance store Port Harcourt',
    'perfume vendor Port Harcourt',
  ],
  onitsha: [
    'perfume shop in Onitsha',
    'buy perfume in Onitsha',
    'perfume store Onitsha',
    'original perfume Onitsha',
    'perfume vendor Onitsha',
    'Onitsha Main Market perfume',
  ],
  anambra: [
    'perfume shop in Anambra',
    'fragrance shop Anambra State',
    'perfume vendor Awka',
    'perfume shop Nnewi',
    'buy perfume Anambra State',
  ],
  enugu: [
    'perfume shop in Enugu',
    'buy perfume in Enugu',
    'perfume delivery Enugu',
    'original perfume Enugu',
    'fragrance store Enugu',
    'perfume vendor Enugu',
  ],
  national: [
    'best perfume store in Nigeria',
    'buy original perfume online Nigeria',
    'Arabian perfume Nigeria',
    'luxury perfume Nigeria',
    'perfume vendor Nigeria',
    'order perfume online Nigeria',
  ],
};

export const HYPER_LOCAL_AREAS = [
  'New Owerri',
  'Ikenegbu',
  'World Bank',
  'MCC Road',
  'Douglas Road',
  'Wetheral Road',
  'Orji',
  'Amakohia',
  'Egbu',
  'Nekede',
  'Ihiagwa',
  'FUTO',
  'Imo State University',
  'Alvan Ikoku',
  'Sam Mbakwe Airport',
  'Shoprite Owerri',
  'Relief Market',
  'Owerri Municipal',
  'Uratta',
  'Okigwe',
  'Orlu',
  'Mbaise',
  'Oguta',
];

export const TRENDING_PERFUME_KEYWORDS = [
  'trending perfumes in Nigeria',
  'vanilla gourmand perfume',
  'pistachio perfume',
  'coconut perfume',
  'cherry perfume',
  'oud perfume',
  'unisex fragrance',
  'long lasting perfume',
  'perfume oil that lasts',
  'body mist and hair mist',
  'designer perfume dupes',
  'perfume layering',
];

export const TRENDING_NOTES = [
  'vanilla',
  'pistachio',
  'caramel',
  'praline',
  'almond',
  'coconut',
  'coffee',
  'cherry',
  'jasmine',
  'rose',
  'orange blossom',
  'bergamot',
  'ylang-ylang',
  'iris',
  'saffron',
  'oud',
  'sandalwood',
  'cedar',
  'patchouli',
  'vetiver',
  'tonka bean',
  'amber',
  'white musk',
  'gardenia',
  'peony',
  'blackcurrant',
  'raspberry',
  'lavender',
  'mint',
  'sea salt',
  'aquatic',
  'green tea',
  'tobacco',
  'leather',
  'incense',
];

export const FRAGRANCE_FORMATS = [
  'eau de parfum',
  'eau de toilette',
  'parfum',
  'roll-on perfume oil',
  'attar',
  'body mist',
  'hair mist',
  'room spray',
  'reed diffuser',
  'ultrasonic humidifier',
  'car diffuser',
  'perfume gift set',
  'sample decant',
];

export const INTENT_KEYWORDS = [
  'original perfume',
  'authentic perfume',
  'not fake perfume',
  'long lasting perfume',
  'perfume with strong projection',
  'affordable perfume under 20000 naira',
  'perfume for men',
  'perfume for women',
  'unisex perfume',
  'perfume for office',
  'perfume for church',
  'perfume for Nigerian weather',
  'perfume gift for her',
  'perfume gift for him',
];

export const LOCATION_KEYWORD_LINE =
  'Owerri, Imo State, Port Harcourt, Onitsha, Anambra, Enugu';

export const TRENDING_KEYWORD_LINE =
  'vanilla gourmand, pistachio, coconut, aquatic, jasmine, vetiver, oud and unisex fragrances';

export const keywordText = (groups = Object.values(LOCATION_KEYWORDS)) =>
  [...new Set(groups.flat())].join(', ');
